spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: rootPassword
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    url: jdbc:mysql://localhost:3306/test
    user: root
    password: rootPassword
    contexts: ddl
